In [1]:
import numpy as np

# Creating Arrays

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
x.dtype

dtype('int64')

In [4]:
one_array = np.ones((3,3))
one_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
one_array2 = np.ones((2,3))
one_array2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
one_array2.dtype

dtype('float64')

In [7]:
zero_array = np.zeros((2,2))
zero_array

array([[0., 0.],
       [0., 0.]])

In [8]:
range_array = np.arange(1,11,1)
range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
random_array = np.random.randint(100)
random_array

85

In [10]:
random_array1 = np.random.randint(1,11,size=(3,3))
random_array1

array([[3, 9, 3],
       [6, 8, 7],
       [3, 8, 4]])

In [11]:
random_array1.size

9

In [12]:
random_array1.shape

(3, 3)

In [13]:
random_array2 = np.random.random((3,4))
random_array2

array([[0.27707432, 0.02310243, 0.97166182, 0.8887916 ],
       [0.42006175, 0.46043778, 0.60651209, 0.63125305],
       [0.11341274, 0.04918274, 0.09405751, 0.62071896]])

In [14]:
random_array3 = np.random.rand(3,3)
random_array3

array([[0.59707154, 0.8267334 , 0.4683958 ],
       [0.54380173, 0.49627738, 0.39931726],
       [0.75038363, 0.36303141, 0.88851228]])

In [15]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[6, 5, 4, 3, 8],
       [4, 9, 2, 7, 2],
       [5, 4, 4, 9, 8]])

In [16]:
np.random.seed(0)
random_array = np.random.randint(10,size=(3,5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [18]:
np.unique(random_array1)

array([3, 4, 6, 7, 8, 9])