In [1]:
import numpy as np

# Creating Arrays

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
x.dtype

dtype('int64')

In [4]:
one_array = np.ones((3,3))
one_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
one_array2 = np.ones((2,3))
one_array2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
one_array2.dtype

dtype('float64')

In [7]:
zero_array = np.zeros((2,2))
zero_array

array([[0., 0.],
       [0., 0.]])

In [8]:
range_array = np.arange(1,11,1)
range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
random_array = np.random.randint(100)
random_array

48

In [10]:
random_array1 = np.random.randint(1,11,size=(3,3))
random_array1

array([[9, 1, 4],
       [1, 4, 4],
       [1, 6, 5]])

In [11]:
random_array1.size

9

In [12]:
random_array1.shape

(3, 3)

In [13]:
random_array2 = np.random.random((3,4))
random_array2

array([[0.50272463, 0.9504173 , 0.65410101, 0.88052445],
       [0.63924564, 0.91384811, 0.99257485, 0.11725268],
       [0.68570593, 0.74391504, 0.33376231, 0.5300818 ]])

In [14]:
random_array3 = np.random.rand(3,3)
random_array3

array([[0.79029988, 0.58502001, 0.62046109],
       [0.50375367, 0.45063062, 0.46374227],
       [0.39680763, 0.88964182, 0.86936831]])

In [15]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[8, 0, 3, 6, 6],
       [7, 9, 2, 7, 9],
       [0, 0, 8, 5, 9]])

In [16]:
np.random.seed(0)
random_array = np.random.randint(10,size=(3,5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])