In [1]:
import numpy as np

In [2]:
random_array = np.random.randint(10, size=(2,3,4,5))
random_array

array([[[[0, 9, 3, 0, 6],
         [6, 1, 8, 5, 3],
         [6, 3, 3, 9, 0],
         [4, 3, 9, 6, 0]],

        [[9, 0, 7, 4, 4],
         [5, 0, 6, 8, 8],
         [4, 1, 1, 5, 0],
         [0, 4, 0, 8, 5]],

        [[3, 8, 2, 9, 0],
         [1, 6, 9, 1, 2],
         [9, 5, 7, 1, 8],
         [0, 5, 6, 2, 9]]],


       [[[9, 1, 8, 2, 0],
         [2, 3, 4, 1, 2],
         [0, 0, 5, 3, 8],
         [2, 4, 4, 7, 0]],

        [[2, 4, 2, 4, 9],
         [4, 0, 5, 1, 2],
         [7, 5, 2, 2, 8],
         [6, 0, 9, 7, 3]],

        [[1, 8, 9, 9, 1],
         [7, 6, 0, 3, 1],
         [6, 0, 8, 2, 2],
         [7, 9, 1, 1, 4]]]])

In [3]:
random_array.size, random_array.shape, random_array.ndim

(120, (2, 3, 4, 5), 4)

In [4]:
random_array[:, :, :, :3]

array([[[[0, 9, 3],
         [6, 1, 8],
         [6, 3, 3],
         [4, 3, 9]],

        [[9, 0, 7],
         [5, 0, 6],
         [4, 1, 1],
         [0, 4, 0]],

        [[3, 8, 2],
         [1, 6, 9],
         [9, 5, 7],
         [0, 5, 6]]],


       [[[9, 1, 8],
         [2, 3, 4],
         [0, 0, 5],
         [2, 4, 4]],

        [[2, 4, 2],
         [4, 0, 5],
         [7, 5, 2],
         [6, 0, 9]],

        [[1, 8, 9],
         [7, 6, 0],
         [6, 0, 8],
         [7, 9, 1]]]])

In [5]:
random_array[:, :, :, :4]

array([[[[0, 9, 3, 0],
         [6, 1, 8, 5],
         [6, 3, 3, 9],
         [4, 3, 9, 6]],

        [[9, 0, 7, 4],
         [5, 0, 6, 8],
         [4, 1, 1, 5],
         [0, 4, 0, 8]],

        [[3, 8, 2, 9],
         [1, 6, 9, 1],
         [9, 5, 7, 1],
         [0, 5, 6, 2]]],


       [[[9, 1, 8, 2],
         [2, 3, 4, 1],
         [0, 0, 5, 3],
         [2, 4, 4, 7]],

        [[2, 4, 2, 4],
         [4, 0, 5, 1],
         [7, 5, 2, 2],
         [6, 0, 9, 7]],

        [[1, 8, 9, 9],
         [7, 6, 0, 3],
         [6, 0, 8, 2],
         [7, 9, 1, 1]]]])

In [6]:
random_array

array([[[[0, 9, 3, 0, 6],
         [6, 1, 8, 5, 3],
         [6, 3, 3, 9, 0],
         [4, 3, 9, 6, 0]],

        [[9, 0, 7, 4, 4],
         [5, 0, 6, 8, 8],
         [4, 1, 1, 5, 0],
         [0, 4, 0, 8, 5]],

        [[3, 8, 2, 9, 0],
         [1, 6, 9, 1, 2],
         [9, 5, 7, 1, 8],
         [0, 5, 6, 2, 9]]],


       [[[9, 1, 8, 2, 0],
         [2, 3, 4, 1, 2],
         [0, 0, 5, 3, 8],
         [2, 4, 4, 7, 0]],

        [[2, 4, 2, 4, 9],
         [4, 0, 5, 1, 2],
         [7, 5, 2, 2, 8],
         [6, 0, 9, 7, 3]],

        [[1, 8, 9, 9, 1],
         [7, 6, 0, 3, 1],
         [6, 0, 8, 2, 2],
         [7, 9, 1, 1, 4]]]])

In [7]:
random_array[:, :, :, 2:4]

array([[[[3, 0],
         [8, 5],
         [3, 9],
         [9, 6]],

        [[7, 4],
         [6, 8],
         [1, 5],
         [0, 8]],

        [[2, 9],
         [9, 1],
         [7, 1],
         [6, 2]]],


       [[[8, 2],
         [4, 1],
         [5, 3],
         [4, 7]],

        [[2, 4],
         [5, 1],
         [2, 2],
         [9, 7]],

        [[9, 9],
         [0, 3],
         [8, 2],
         [1, 1]]]])

In [8]:
random_array

array([[[[0, 9, 3, 0, 6],
         [6, 1, 8, 5, 3],
         [6, 3, 3, 9, 0],
         [4, 3, 9, 6, 0]],

        [[9, 0, 7, 4, 4],
         [5, 0, 6, 8, 8],
         [4, 1, 1, 5, 0],
         [0, 4, 0, 8, 5]],

        [[3, 8, 2, 9, 0],
         [1, 6, 9, 1, 2],
         [9, 5, 7, 1, 8],
         [0, 5, 6, 2, 9]]],


       [[[9, 1, 8, 2, 0],
         [2, 3, 4, 1, 2],
         [0, 0, 5, 3, 8],
         [2, 4, 4, 7, 0]],

        [[2, 4, 2, 4, 9],
         [4, 0, 5, 1, 2],
         [7, 5, 2, 2, 8],
         [6, 0, 9, 7, 3]],

        [[1, 8, 9, 9, 1],
         [7, 6, 0, 3, 1],
         [6, 0, 8, 2, 2],
         [7, 9, 1, 1, 4]]]])

In [9]:
random_array[:1,:2,:,:]

array([[[[0, 9, 3, 0, 6],
         [6, 1, 8, 5, 3],
         [6, 3, 3, 9, 0],
         [4, 3, 9, 6, 0]],

        [[9, 0, 7, 4, 4],
         [5, 0, 6, 8, 8],
         [4, 1, 1, 5, 0],
         [0, 4, 0, 8, 5]]]])