In [2]:
import numpy as np

# Data types and Attributes

In [3]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

ndarray is the only data type in NumPy

In [11]:
y = np.array([[1,2,3],
              [4,5,6],
              [3,6,7]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 7]])

In [12]:
z=np.array([[2,3.4,6.7],
            [6,9,0.1],
            [5,2,3]])
z

array([[2. , 3.4, 6.7],
       [6. , 9. , 0.1],
       [5. , 2. , 3. ]])

In [13]:
x1=np.array([[[1,2,3],
              [4,5,6],
              [3,7,4.2]],
             [[2.6,4.8,2.2],
              [1,7,8],
              [3.6,8.8,0.7]]])
x1

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [3. , 7. , 4.2]],

       [[2.6, 4.8, 2.2],
        [1. , 7. , 8. ],
        [3.6, 8.8, 0.7]]])

In [15]:
x.shape

(3,)

In [16]:
y.shape

(3, 3)

In [17]:
z.shape

(3, 3)

In [18]:
x1.shape

(2, 3, 3)

In [19]:
x.ndim, y.ndim, z.ndim, x1.ndim

(1, 2, 2, 3)

In [21]:
x.dtype, y.dtype, z.dtype, x1.dtype

(dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'))

In [22]:
x.size, y.size, z.size, x1.size

(3, 9, 9, 18)

In [23]:
type(x), type(y), type(z), type(x1)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [24]:
import pandas as pd

In [27]:
z

array([[2. , 3.4, 6.7],
       [6. , 9. , 0.1],
       [5. , 2. , 3. ]])

In [28]:
df = pd.DataFrame(z)
df

0    1    2
0  2.0  3.4  6.7
1  6.0  9.0  0.1
2  5.0  2.0  3.0